Parameters:
  bucketName: 
    type: string

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref bucketName
      LifecycleConfiguration:
        Rules:
          - Id: LogLifecycleManagement
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
            ExpirationInDays: 365
